
[window]
padding = { x = 20, y = 20}
opacity = 0.9

[font]
size = 12.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[general]

import = ["~/.config/alacritty/current_theme.toml"]
