[colors.primary]
background = "#303446"
foreground = "#c6d0f5"

[colors.cursor]
text = "#303446"
cursor = "#f2d5cf"

[colors.normal]
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#ca9ee6"
cyan = "#81c8be"
white = "#b5bfe2"

[colors.bright]
black = "#626880"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#ca9ee6"
cyan = "#81c8be"
white = "#a5adce"
